### ISSUE TITLE
Upgrade sveltekit

### ISSUE THREAD

**Issue by lindgr3n** [lindgr3n/breeze-sveltekit#3]

**Comment by twent** [comment]
Thank you 👍 Waiting for this 🙂
But I'll try it myself before

**Comment by lindgr3n** [comment]
A bit slow, but merged now. Still need some work but now follows the new SvelteKit folder structure.

**Comment by twent** [comment]
> A bit slow, but merged now. Still need some work but now follows the new SvelteKit folder structure.

Thank you very much!
