### ISSUE TITLE
Old user data persisting in store before being loaded over

### ISSUE THREAD

**Issue by jakecausier** [lindgr3n/breeze-sveltekit#5]
Hi there, great repo, it's been quite helpful for me to understand how sveltekit can work with my Breeze backend.

I've run into an issue with multiple user accounts. It appears as though a previous user will be persisted when another account is being used. Here are some steps on how to replicate it:

1. Log in as User 1
2. Check the dashboard, User 1's name is in the top right
3. Log out through the dropdown
4. Log in as User 2
5. Check the dashboard, there will be User 1's name visible in the top right, before being overwritten with User 2's name

I've determined the switchover happens when PageData sets the new user state in `/routes/(app)/dashboard/+page.svelte`, commenting this out however causes the user state to turn `undefined` after the initial User 1 name flash.

Do you have any suggestions on fixing this please? Thanks.

**Comment by lindgr3n** [comment]
Thanks for trying it out. Will see if I can find an issue with this in the next couple of days 👍

**Comment by BennySama94** [comment]
You can import the User-Store in the Hooks and the Logout TypeScript files, and put a "user.set(null);" in the Catch in hooks or in the logout logic respectively.

**Comment by lindgr3n** [comment]
Sorry for the delay.  More like a few weeks than days 🤦‍♂️ Tried this out now and I did not manage to reproduce the issue.
Still did think a bit about it and ended up removing the user store and just making use of how SvelteKit returns the PageData. Felt a bit more straightforward.

Also updated the dependencies.

Feel free to reopen if it did not help :)
